/** RUNI intro per subcategory slug. Unique wording, supplier voice, no claims beyond the range. */
export const subcategoryCopy = {
  'system-scaffolds-ringlock': 'Ringlock standards, ledgers, diagonals, base collars, planks and stairs held in Eindhoven for contractors and rental fleets that need parts to match stock they already run. Send the system and node dimensions with your enquiry and we confirm fit before quoting.',
  'system-scaffolds-hk': 'HK system scaffold components for sites that standardised on the HK pattern. Supplied to order in full sets or as top up quantities, with delivery across the Benelux and Germany.',
  'system-scaffold-cuplock': 'Cuplock standards, ledgers, cups and braces for the most widely used system in the Netherlands and Belgium. Common lengths stocked, special lengths made to order.',
  'load-bearing-system-shoring-tower': 'Shoring tower frames, jacks and braces for slab and beam support. Supplied per tower height with base and head jacks, quoted against your load case.',
  'accessories-jacks-nuts': 'Adjustable base jacks, U head jacks and prop nuts in the thread sizes used across European system scaffolds. Sold by the piece or the pallet from Eindhoven.',
  'access-scaffold-american-frame': 'H frame and walk through frame sets with cross braces, planks and couplers for facade access. A frame set for one gable or a container for a fleet.',
  'access-scaffold-euro-frame': 'Euro frame facade scaffold components for refurbishment and housing sites, supplied with guard rails and toe boards to match.',
  'slab-formwork-system-props': 'Adjustable steel props in the standard European lengths, stocked in Eindhoven for slab and beam formwork. Tell us the class and the length range and we quote the same day.',
  'slab-formwork-system-fork-heads': 'Fork heads and U heads for timber beam slab formwork, sized for the beams and props used on Dutch and German sites.',
  'system-slab-formwork-tripods': 'Prop tripods that hold a prop upright while a slab deck is set. Sold in tens or hundreds, to match prop quantities.',
  'formwork-accessories': 'Tie rods, wing nuts, anchor nuts, water stops and waler plates for wall and column formwork, stocked as consumables for formwork contractors.',
  'wall-formwork-systems-clamps-panels': 'Wall formwork clamps, wedge clamps and steel panels for concrete wall and column casting, supplied in the sizes formwork crews reuse job after job.',
  'scaffold-tube-fitting-european': 'Pressed and forged scaffold couplers to EN 74-1 in right angle, swivel, sleeve, putlog and beam patterns, held in Eindhoven for tube and fitting scaffolders.',
  'scaffold-tube-fitting-british-american': 'BS 1139 pattern drop forged fittings for contractors working to British practice or with mixed fleets, supplied alongside the European range.',
  'security-systems-guard-rails-railing-posts': 'Guard rails, railing posts and toe boards for edge protection on scaffolds and slabs. Sold to complete a scaffold set or to replace fleet losses.',
  'trestles-barriers': 'Builders trestles and site barriers for bricklayers and site control, delivered from stock across the Netherlands and Belgium.',
  cattle: 'Cubicles, headlocks, feed barriers, troughs and feeders for dairy and beef housing. We prepare the parts list from your shed plan and deliver as one consignment.',
  calves: 'Calf pens and pail rings for rearing sheds, in standard modules that extend as the herd grows.',
  sheep: 'Sheep hurdles, panels, headlocks, hay baskets, feeders and race sections for handling systems on farms in the Benelux and beyond.',
  pigs: 'Farrowing and gestation penning with stainless fittings for pig units, supplied to the layout of the house.',
  horse: 'Stable partitions, doors and handling components in galvanised steel for yards and livery stables.',
  'field-gates': 'Galvanised field gates, pasture gates, adjustable gates, posts and fittings in the common metric widths, stocked for farms and installers.',
  'post-supports': 'Bolt down and concrete in post supports for fencing, decking and pergolas, sold by the carton and the pallet to merchants and installers across Europe.',
  'adjustable-post-supports': 'Height adjustable post supports for decking and timber frames on uneven ground, supplied in the standard European post sizes.',
  'pole-anchors-ground-plates': 'Spiral and bolt type ground anchors and ground plates for posts without concrete, stocked for the spring fencing season.',
  'post-caps': 'Post caps and finials that protect post ends and finish a fence line, in the sizes that match our post supports.',
  'miscellaneous-products': 'Garden and fencing accessories that complete a hardware order, from brackets to fittings, supplied alongside the post support range.',
  'indoor-wood-connectors': 'Joist hangers, angle brackets and perforated plates in common European widths for timber frame builders, roofers and merchants.',
  'rolling-towers': 'Complete RALUTECH aluminium rolling towers in 75 × 250 cm and 150 × 250 cm, up to 850 cm working height, each supplied with its full parts list.',
  'rolling-tower-components': 'RALUTECH frames, braces, decks, castors, ladders, toe boards, stabilisers and clips, each available separately by article number.',
};
